name: Construir y publicar imagen Docker
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Construir y publicar imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USER }}/univalle-prueba:latest .
      - name: Publicar imagen Docker
        run: docker push ${{ secrets.DOCKER_USER }}/univalle-prueba:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo (obtener docker-compose.yml, setup_vm.sh)
        uses: actions/checkout@v5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # Configurar acceso ssh
      - name: Configurar agente SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Copiar el script de configuracion a la VM de OCI    
      - name: Copiar script de configuracion a la VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "setup_vm.sh"
          target: "/tmp/"
      # Ejecutar script de configuracion en la VM de OCI
      - name: Ejecutar script de instalacion de docker en la VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x /tmp/setup_vm.sh
            /tmp/setup_vm.sh ${{ secrets.SSH_USER }}
            rm /tmp/setup_vm.sh # Eliminar script por seguridad
      # Copiar el docker-compose.yml a la VM de OCI
      - name: Copiar docker-compose.yml a la VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker.compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/deploy/"
      # Ejecutar docker-compose en la VM de OCI
      - name: Ejecutar docker-compose en la VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DEPLOY_PATH="/home/${{ secrets.SSH_USER }}/deploy"
            cd $DEPLOY_PATH
            
            # Detener y limpiar servicios anteriores 
            sudo docker-compose down
            
            # Descargar la imagen desde docker hub
            echo ${{ secrets.DOCKER_PAT }} | sudo docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
            sudo docker-compose pull
            sudo docker-compose up -d --force-recreate
            sudo docker logout
  send_email:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          subject: "Despliegue completado"
          body: "El despliegue de la aplicación se ha completado exitosamente. http://${{ secrets.SSH_HOST }}"
          to: gonchi.028@gmail.com
          from: Luke Skywalker
